### PR TITLE
fix for null value in convertToDatabaseValue

### PR DESCRIPTION
**Pull request by moesoha**

### CODE REVIEW

**Comment by sunchaserinfo** [comment]
Have you tested it? I have no project with this lib so I will have to trust you :D

**Comment by sunchaserinfo** [comment]
Also please update your code style to [PSR](https://www.php-fig.org/psr/psr-12/), change `else if` to `elseif`

**Comment by moesoha** [comment]
Sure, I have tested with the null value.

image

This will raise an exception before:

    Could not convert PHP value of type 'NULL' to type 'inet'. Expected one of the following types: null, Leth\IPAddress\IP\Address, Leth\IPAddress\IP\NetworkAddress

**Comment by sunchaserinfo** [comment]
Released as 1.1.1. Thanks!

**Pull request merged**
